Repository thoth-station/help, pull requests merged in 2022-05, with the labels that each got.

#2 init
  .aicoe-ci.yaml
  .github/workflows/build.yaml
  .pre-commit-config.yaml
  .prow.yaml
  .thoth.yaml
  LICENSE
  OWNERS
  README.md
  app.py
  config/content-sources.yaml
  config/documentation.yaml
  config/toc-sources.yaml
  content/documentation/index.md
  content/index.md
  content/logo.png
  gatsby-browser.js
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  src/components/Header.js
  src/components/Layout.js
  src/components/NavSidebar.js
  src/components/Seo.js
  src/normalize.css
  src/pages/404.js
  src/style.css
  src/templates/Mdx.js
  static/favicon.ico
  static/robots.txt
Labels: size/XXL

#5 added cron job and fixed bug
  .github/workflows/build.yaml
  gatsby-config.js
Labels: size/XS, approved

#6 prettier and added script command
  README.md
  content/documentation/index.md
  content/index.md
  gatsby-browser.js
  gatsby-config.js
  gatsby-node.js
  package.json
  src/components/Header.js
  src/components/Layout.js
  src/components/NavSidebar.js
  src/components/Seo.js
  src/pages/404.js
  src/templates/Mdx.js
Labels: approved, size/L

#7 added gh-pages package
  package-lock.json
  package.json
Labels: approved, size/L

#8 re run github action
  README.md
Labels: size/XS, approved

#9 Landing page
  content/index.md
  gatsby-browser.js
  gatsby-config.js
  package-lock.json
  package.json
  src/components/Footer.js
  src/components/Footer.scss
  src/components/Header.js
  src/components/Layout.js
  src/components/Layout.scss
  src/components/logo.png
  src/normalize.css
  src/style.css
  src/templates/Mdx.js
Labels: size/XXL, approved

#11 added rh logo
  src/components/RHLogo.png
Labels: size/XS, approved

#12 fixed links in prod
  src/components/Header.js
  src/components/NavSidebar.js
Labels: approved, size/S

#13 Nav Bar Toggle Fix
  src/components/Header.js
Labels: size/XS, approved

#14 footer and links
  content/index.md
  src/components/Footer.js
  src/components/Footer.scss
  src/components/Header.js
  src/components/NavSidebar.js
  src/components/footer_logo.png
Labels: approved, size/L

#15 added content
  config/documentation.yaml
  content/documentation/index.md
  content/metrics/index.md
  content/support/index.md
  gatsby-config.js
  gatsby-node.js
  src/components/Header.js
  src/components/NavSidebar.js
Labels: approved, size/L

#16 added support for non mdx files
  content/index.mdx
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  src/components/Layout.js
  src/components/Layout.scss
  src/templates/MarkdownRemark.js
  src/templates/Mdx.js
Labels: size/XXL, approved

#20 Add google analytics dashboard to website
  content/metrics/index.md
Labels: approved
